name: learn-github-actions 
on: [job]
jobs:
  check-bats-version : 
    runs-on : ubutu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
          with:
          node-version: '18'
      - run: npm install -g bats
      - run: bats -v

     